#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jiaju_shop?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:com/mlz/mapper/maping/mapper/*.xml
  type-aliases-package: com.mlz.entity
#mybatis plus